maze_data:
  goal:
  - - 5
    - 8
  - - 6
    - 8
  - - 5
    - 7
  - - 6
    - 7
  max_step_val: 440
  maze_size: 21
  wall:
  - 14
  - 4
  - 4
  - 6
  - 5
  - 12
  - 6
  - 6
  - 5
  - 13
  - 13
  - 13
  - 13
  - 12
  - 6
  - 6
  - 4
  - 6
  - 4
  - 6
  - 5
  - 14
  - 1
  - 8
  - 6
  - 3
  - 10
  - 4
  - 6
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 4
  - 4
  - 2
  - 6
  - 1
  - 13
  - 9
  - 12
  - 2
  - 1
  - 12
  - 5
  - 12
  - 1
  - 14
  - 1
  - 9
  - 9
  - 9
  - 9
  - 9
  - 11
  - 11
  - 14
  - 6
  - 3
  - 9
  - 9
  - 9
  - 12
  - 0
  - 1
  - 8
  - 3
  - 10
  - 6
  - 2
  - 2
  - 3
  - 11
  - 8
  - 3
  - 12
  - 4
  - 4
  - 6
  - 4
  - 1
  - 9
  - 8
  - 3
  - 9
  - 10
  - 3
  - 14
  - 4
  - 4
  - 7
  - 12
  - 6
  - 5
  - 11
  - 14
  - 1
  - 9
  - 9
  - 13
  - 11
  - 9
  - 9
  - 8
  - 6
  - 2
  - 5
  - 12
  - 6
  - 3
  - 8
  - 5
  - 9
  - 12
  - 2
  - 6
  - 4
  - 0
  - 2
  - 0
  - 2
  - 6
  - 1
  - 9
  - 8
  - 4
  - 4
  - 3
  - 10
  - 5
  - 13
  - 10
  - 3
  - 10
  - 3
  - 13
  - 12
  - 3
  - 8
  - 5
  - 9
  - 14
  - 7
  - 9
  - 9
  - 9
  - 11
  - 9
  - 12
  - 4
  - 2
  - 1
  - 12
  - 6
  - 4
  - 6
  - 1
  - 8
  - 4
  - 1
  - 10
  - 0
  - 6
  - 6
  - 1
  - 9
  - 8
  - 6
  - 1
  - 9
  - 10
  - 4
  - 2
  - 1
  - 12
  - 0
  - 6
  - 1
  - 9
  - 9
  - 8
  - 6
  - 2
  - 4
  - 6
  - 0
  - 1
  - 8
  - 6
  - 1
  - 10
  - 6
  - 3
  - 12
  - 2
  - 1
  - 8
  - 5
  - 9
  - 10
  - 0
  - 3
  - 14
  - 4
  - 3
  - 14
  - 1
  - 9
  - 10
  - 5
  - 9
  - 12
  - 4
  - 5
  - 9
  - 12
  - 2
  - 1
  - 8
  - 1
  - 14
  - 2
  - 7
  - 12
  - 2
  - 4
  - 6
  - 1
  - 9
  - 12
  - 2
  - 1
  - 9
  - 9
  - 9
  - 11
  - 10
  - 4
  - 2
  - 1
  - 8
  - 4
  - 6
  - 5
  - 8
  - 6
  - 0
  - 6
  - 0
  - 1
  - 8
  - 6
  - 2
  - 2
  - 2
  - 2
  - 7
  - 13
  - 10
  - 4
  - 2
  - 1
  - 8
  - 5
  - 9
  - 8
  - 6
  - 0
  - 6
  - 1
  - 9
  - 9
  - 12
  - 6
  - 6
  - 6
  - 6
  - 6
  - 0
  - 5
  - 10
  - 4
  - 2
  - 1
  - 8
  - 1
  - 8
  - 6
  - 0
  - 6
  - 1
  - 9
  - 9
  - 9
  - 12
  - 6
  - 6
  - 6
  - 5
  - 9
  - 8
  - 5
  - 10
  - 4
  - 2
  - 1
  - 9
  - 8
  - 6
  - 0
  - 6
  - 1
  - 9
  - 9
  - 9
  - 9
  - 12
  - 6
  - 5
  - 9
  - 8
  - 1
  - 9
  - 14
  - 2
  - 4
  - 2
  - 1
  - 10
  - 6
  - 1
  - 13
  - 9
  - 9
  - 9
  - 9
  - 9
  - 10
  - 5
  - 9
  - 9
  - 9
  - 8
  - 2
  - 4
  - 5
  - 10
  - 5
  - 10
  - 5
  - 14
  - 0
  - 2
  - 2
  - 1
  - 9
  - 9
  - 10
  - 6
  - 3
  - 9
  - 9
  - 9
  - 10
  - 5
  - 9
  - 10
  - 5
  - 10
  - 5
  - 10
  - 5
  - 9
  - 12
  - 7
  - 9
  - 9
  - 10
  - 6
  - 6
  - 6
  - 3
  - 9
  - 8
  - 4
  - 0
  - 2
  - 5
  - 10
  - 5
  - 10
  - 6
  - 2
  - 2
  - 2
  - 4
  - 1
  - 8
  - 6
  - 6
  - 6
  - 6
  - 6
  - 3
  - 9
  - 9
  - 8
  - 6
  - 0
  - 6
  - 0
  - 6
  - 6
  - 6
  - 4
  - 6
  - 1
  - 9
  - 10
  - 6
  - 6
  - 6
  - 6
  - 6
  - 6
  - 2
  - 2
  - 2
  - 6
  - 2
  - 6
  - 2
  - 6
  - 6
  - 6
  - 2
  - 6
  - 2
  - 3
