maze_data:
  goal:
  - - 17
    - 10
  - - 18
    - 10
  - - 17
    - 9
  - - 18
    - 9
  max_step_val: 440
  maze_size: 21
  wall:
  - 14
  - 4
  - 4
  - 6
  - 5
  - 12
  - 6
  - 6
  - 5
  - 13
  - 13
  - 13
  - 13
  - 12
  - 6
  - 6
  - 4
  - 6
  - 4
  - 4
  - 5
  - 14
  - 1
  - 8
  - 6
  - 2
  - 2
  - 4
  - 6
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 4
  - 4
  - 2
  - 6
  - 1
  - 9
  - 9
  - 12
  - 2
  - 1
  - 12
  - 5
  - 12
  - 1
  - 14
  - 1
  - 11
  - 11
  - 9
  - 9
  - 9
  - 11
  - 11
  - 14
  - 6
  - 3
  - 9
  - 9
  - 11
  - 12
  - 0
  - 1
  - 8
  - 3
  - 10
  - 6
  - 3
  - 14
  - 4
  - 1
  - 8
  - 3
  - 12
  - 4
  - 4
  - 6
  - 4
  - 1
  - 9
  - 14
  - 3
  - 11
  - 10
  - 3
  - 14
  - 4
  - 6
  - 6
  - 4
  - 3
  - 10
  - 3
  - 14
  - 1
  - 9
  - 9
  - 13
  - 11
  - 9
  - 9
  - 14
  - 4
  - 4
  - 4
  - 5
  - 12
  - 3
  - 12
  - 5
  - 9
  - 12
  - 6
  - 6
  - 7
  - 10
  - 2
  - 0
  - 2
  - 6
  - 1
  - 9
  - 14
  - 3
  - 11
  - 11
  - 8
  - 1
  - 13
  - 9
  - 11
  - 10
  - 3
  - 13
  - 13
  - 13
  - 13
  - 13
  - 9
  - 14
  - 7
  - 9
  - 9
  - 14
  - 5
  - 13
  - 12
  - 1
  - 9
  - 8
  - 2
  - 6
  - 4
  - 6
  - 2
  - 0
  - 0
  - 0
  - 2
  - 0
  - 6
  - 6
  - 1
  - 9
  - 13
  - 10
  - 0
  - 1
  - 10
  - 1
  - 10
  - 5
  - 14
  - 0
  - 6
  - 5
  - 9
  - 9
  - 8
  - 6
  - 0
  - 6
  - 6
  - 1
  - 9
  - 9
  - 12
  - 3
  - 10
  - 6
  - 1
  - 12
  - 2
  - 5
  - 10
  - 5
  - 9
  - 10
  - 0
  - 3
  - 14
  - 1
  - 15
  - 13
  - 9
  - 9
  - 8
  - 1
  - 13
  - 13
  - 12
  - 1
  - 8
  - 5
  - 10
  - 4
  - 2
  - 1
  - 14
  - 2
  - 7
  - 13
  - 10
  - 4
  - 0
  - 1
  - 9
  - 9
  - 11
  - 9
  - 9
  - 9
  - 9
  - 11
  - 9
  - 12
  - 2
  - 4
  - 2
  - 4
  - 6
  - 5
  - 8
  - 6
  - 1
  - 9
  - 9
  - 9
  - 9
  - 14
  - 1
  - 9
  - 10
  - 2
  - 7
  - 9
  - 10
  - 4
  - 2
  - 4
  - 2
  - 5
  - 9
  - 8
  - 6
  - 1
  - 9
  - 9
  - 9
  - 8
  - 5
  - 8
  - 1
  - 13
  - 12
  - 5
  - 9
  - 13
  - 10
  - 4
  - 2
  - 5
  - 8
  - 1
  - 8
  - 6
  - 1
  - 9
  - 9
  - 9
  - 9
  - 9
  - 9
  - 9
  - 11
  - 9
  - 11
  - 9
  - 10
  - 5
  - 10
  - 4
  - 2
  - 1
  - 9
  - 8
  - 6
  - 1
  - 9
  - 8
  - 1
  - 9
  - 9
  - 9
  - 9
  - 12
  - 2
  - 4
  - 2
  - 6
  - 2
  - 6
  - 2
  - 6
  - 2
  - 1
  - 10
  - 6
  - 3
  - 11
  - 9
  - 9
  - 11
  - 9
  - 9
  - 9
  - 9
  - 13
  - 11
  - 14
  - 4
  - 4
  - 6
  - 5
  - 14
  - 5
  - 10
  - 5
  - 14
  - 4
  - 5
  - 11
  - 9
  - 13
  - 9
  - 9
  - 8
  - 3
  - 9
  - 13
  - 12
  - 3
  - 8
  - 5
  - 8
  - 5
  - 10
  - 5
  - 10
  - 5
  - 11
  - 8
  - 7
  - 9
  - 9
  - 10
  - 3
  - 8
  - 6
  - 3
  - 8
  - 1
  - 13
  - 10
  - 3
  - 11
  - 10
  - 4
  - 2
  - 6
  - 2
  - 5
  - 9
  - 13
  - 9
  - 8
  - 6
  - 4
  - 2
  - 7
  - 12
  - 3
  - 9
  - 10
  - 6
  - 6
  - 4
  - 7
  - 10
  - 4
  - 6
  - 6
  - 3
  - 9
  - 9
  - 11
  - 10
  - 6
  - 2
  - 6
  - 6
  - 2
  - 6
  - 2
  - 6
  - 6
  - 7
  - 10
  - 6
  - 6
  - 2
  - 6
  - 6
  - 6
  - 2
  - 2
  - 7
