maze_data:
  goal:
  - - 7
    - 8
  - - 8
    - 8
  - - 7
    - 7
  - - 8
    - 7
  max_step_val: 255
  maze_size: 16
  wall:
  - 14
  - 6
  - 6
  - 6
  - 6
  - 6
  - 6
  - 4
  - 6
  - 4
  - 6
  - 4
  - 6
  - 6
  - 6
  - 5
  - 12
  - 6
  - 4
  - 6
  - 5
  - 14
  - 4
  - 2
  - 7
  - 9
  - 14
  - 2
  - 6
  - 5
  - 13
  - 9
  - 8
  - 5
  - 9
  - 12
  - 3
  - 12
  - 3
  - 12
  - 5
  - 9
  - 14
  - 4
  - 6
  - 3
  - 9
  - 9
  - 11
  - 9
  - 9
  - 9
  - 12
  - 3
  - 14
  - 1
  - 10
  - 1
  - 14
  - 2
  - 6
  - 5
  - 9
  - 9
  - 13
  - 9
  - 10
  - 2
  - 3
  - 12
  - 5
  - 9
  - 13
  - 9
  - 14
  - 4
  - 6
  - 3
  - 9
  - 9
  - 9
  - 9
  - 12
  - 5
  - 12
  - 1
  - 9
  - 11
  - 10
  - 1
  - 12
  - 2
  - 6
  - 5
  - 9
  - 9
  - 9
  - 9
  - 9
  - 10
  - 3
  - 9
  - 8
  - 6
  - 6
  - 1
  - 9
  - 12
  - 4
  - 1
  - 10
  - 3
  - 9
  - 10
  - 2
  - 6
  - 7
  - 11
  - 11
  - 12
  - 5
  - 9
  - 10
  - 3
  - 11
  - 10
  - 6
  - 5
  - 8
  - 6
  - 5
  - 14
  - 6
  - 4
  - 6
  - 2
  - 3
  - 11
  - 12
  - 6
  - 4
  - 6
  - 4
  - 1
  - 9
  - 13
  - 8
  - 6
  - 6
  - 1
  - 12
  - 5
  - 12
  - 5
  - 10
  - 4
  - 2
  - 4
  - 3
  - 9
  - 8
  - 1
  - 10
  - 4
  - 7
  - 11
  - 9
  - 9
  - 9
  - 9
  - 12
  - 3
  - 12
  - 3
  - 12
  - 1
  - 9
  - 10
  - 5
  - 10
  - 6
  - 7
  - 10
  - 1
  - 9
  - 9
  - 10
  - 4
  - 3
  - 12
  - 1
  - 9
  - 9
  - 12
  - 2
  - 4
  - 7
  - 14
  - 6
  - 1
  - 9
  - 9
  - 12
  - 3
  - 12
  - 3
  - 11
  - 9
  - 11
  - 8
  - 6
  - 2
  - 4
  - 6
  - 7
  - 9
  - 9
  - 8
  - 3
  - 12
  - 3
  - 13
  - 13
  - 9
  - 13
  - 10
  - 5
  - 14
  - 2
  - 4
  - 7
  - 9
  - 10
  - 1
  - 12
  - 3
  - 12
  - 2
  - 1
  - 9
  - 10
  - 6
  - 2
  - 6
  - 6
  - 2
  - 6
  - 2
  - 6
  - 2
  - 2
  - 7
  - 10
  - 6
  - 2
  - 3
